name: Docker build and publish

on:
  push:
    tags:
      - '*.*.*.*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_BASE_NAME: alpine-tor-gw
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit tag
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "TAG is ${GITHUB_REF#refs/*/}"

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}

      - name: Test Tor proxy working
        run: |
          docker run -d --name tor_${{ env.COMMIT_TAG }} -p 127.0.0.1:18080:8080 ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
          sleep 15
          IP1=`curl -s ip.me`
          IP2=`all_proxy=http://localhost:18080 curl -s ip.me`
          docker rm -f tor_${{ env.COMMIT_TAG }}
          if [ $IP1 == $IP2 ]; then echo "Failed Tor test: Direct IP = $IP1, Tor IP = $IP2" && exit 1L; else echo "TEST PASS: Direct IP = $IP1, Tor IP = $IP2"; fi
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}

