name: Build and publish docker images

on:
  push:
    tags:
      - '*.*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        # Extract metadata (tags, labels) for Docker
        # https://github.com/docker/metadata-action
        name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      -
        # extract TAG value from commit
        name: Set COMMIT_TAG
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "TAG is $COMMIT_TAG"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-tor-gw:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-tor-gw:${{ env.COMMIT_TAG }}
            ghcr.io/${{ github.repository_owner }}/alpine-tor-gw:latest
            ghcr.io/${{ github.repository_owner }}/alpine-tor-gw:${{ env.COMMIT_TAG }}
