name: Docker build and publish

on:
  push:
    tags:
      - '*.*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_BASE_NAME: alpine-tor-gw
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        # extract TAG value from commit
        name: Extract commit tag
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "TAG is ${GITHUB_REF#refs/*/}"
      -
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
      -
        # let's try running some tests
        name: Test Tor proxy working
        run: |
          docker run -d --name tor_${{ env.COMMIT_TAG }} -p 127.0.0.1:18080:8080 ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
          sleep 15
          IP1=`curl -s ip.me`
          IP2=`all_proxy=http://localhost:18080 curl -s ip.me`
          docker rm -f tor_${{ env.COMMIT_TAG }}
          if [ $IP1 == $IP2 ]; then echo "Failed Tor test: Direct IP = $IP1, Tor IP = $IP2" && exit 1L; else echo "TEST PASS: Direct IP = $IP1, Tor IP = $IP2"; fi
      -
        name: Tag and push to registries
        if: ${{ success() }}
        run: |
          docker tag ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:latest
          docker tag ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
          docker tag ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:latest
          docker tag ${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }} ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:${{ env.COMMIT_TAG }}
